### ISSUE TITLE
keeps crashing

### ISSUE THREAD

**Issue by usernameeeeeeeeeeeeee** [nevoka-be/Issues#2]
crash on startup

**Comment by JayJay1989** [comment]
please use the template.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Logs**
Please use a paste site for large blocks of code/logs: https://gist.github.com/

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Java Version [e.g. 1.8u252]
 - Mod+version [e.g. BetterBedrockGenerator 0.0.6]

**Additional context**
Add any other context about the problem here.

**Comment by usernameeeeeeeeeeeeee** [comment]
hey can you fix it crashing on start up

**Comment by usernameeeeeeeeeeeeee** [comment]
i am using 1.16.4

**Comment by JayJay1989** [comment]
You are saying: there is a crash, not saying what mod.... im going to close this report
